### PR TITLE
Add feature to pile and unpile FITS files

### PR DESCRIPTION
**Pull request by SpheMakh**
I added im.argo.combine_fits() to pile component files from wsclean as part of #9. Now I'm adding a complimentary function to unpile a FITS; im.argo.splitfits().

### CODE REVIEW

**Comment by SpheMakh** [comment]
@o-smirnov, maybe these functions should be added to fitstools.py?

**Comment by o-smirnov** [comment]
Good idea I think!

**Comment by SpheMakh** [comment]
When running multiple instances of CASAPY in one directory some usually crash due to conflicts with log files. The solution ( 24f914c) is to call each CASAPY instance from a different directory.

**Comment by IanHeywood** [comment]
Won't the removal of the temporary folder also delete any image files that CASA has generated? I can't spot the bit where they get rescued...

**Comment by SpheMakh** [comment]
just after I run the casapy, I `cd` back to the working directory. So all images will still be generated in the working directory. (see line 366 in im.argo.py)

**Comment by o-smirnov** [comment]
Ahh, now that's clever. We should do the same in std.runcasapy. Solves the
problem of cleaning up the shit that CASA drops behind.

**Comment by IanHeywood** [comment]
This one?

https://github.com/ska-sa/pyxis/blob/master/Pyxides/im/argo.py

I only get as far as line 316, but I'll take your word for it. :)

**Comment by SpheMakh** [comment]
@IanHeywood follow this link 24f914c, the changes are still only in my fork :) https://github.com/SpheMakh/pyxis/blob/master/Pyxides/im/argo.py

**Comment by IanHeywood** [comment]
Sometimes I know that I know nothing. Thanks man.

**Pull request merged**
