### PR TITLE
Test deploy

### PR DESCRIPTION
**Pull request by Athanaseus**

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
@Athanaseus just note I have a test on the jenkins CI to test the MT suite

**Comment by Athanaseus** [comment]
@bennahugo Yes, I realised with the `docker` files. Here I wanted to test the installations for the respective Python versions.
Also, we can make a release to include it in `Kern-9`.

**Comment by bennahugo** [comment]
LGTM. acceptance tests passed

**Pull request merged**
